### PR TITLE
Optimistic lock approach to ensure sync. over group values

### PR DESCRIPTION
**Pull request by gweisz**
Directly related to: https://github.com/mybatis/memcached-cache/issues/11

Ensures that no group value being added to the group is lost.

The part:

 		boolean jobDone = false;

 		while (!jobDone) {
 		...
 		}

Could be improved thought, maybe throwing an exception after a certain number of retries.

### CODE REVIEW

**Comment by emacarron** [comment]
Hi @gweisz can you please add unit test to your contribution? thanks in advance

**Comment by gweisz** [comment]
There!

**Comment by andever** [comment]
I found the  removeGroup  operation also has the same problem. I try to use delete operation with cas

**Comment by adrianboimvaser** [comment]
Is this project dead? Last release (1.0.0) is from 2014 but I do see recent commits though...

**Comment by hazendaz** [comment]
It's still alive.  I don't think much in actual code has ever had to change this no new release.  However there will be one after mybatis 3.5.0 is released.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@adrianboimvaser Reading the issue it feels to me it was not considered much of a bug as it was extra protection.  I can also see after looking that it's quite possible this missed released in 2016 when nearly everything was released most likely as I was doing them and I didn't have memcache locally.  Anyway, I'll look over the outstanding PRs and work to get a release once mybatis 3.5.0 is released.

Anything at this point is java 8 usage, will that pose any issues for you?

**Comment by adrianboimvaser** [comment]
Well, I ran after this in production just a few days after starting using it and it was really bad.

**Comment by hazendaz** [comment]
@adrianboimvaser @emigioria A new release has been pushed to central.  It will show up in about 2 hours but you can otherwise pull it now.  Version is 1.1.0.  It does require java 8 and will pull in mybatis version 3.5.0.  Let me know if that solves the issues you have run into.  Thanks.

**Pull request merged**
